### ISSUE TITLE
Nuevos paquetes de R o Python para añadir al JupyterHub

### ISSUE THREAD

**Issue by emiliom** [Intercoonecta/tutoriales#1]
Añadan aquí los paquetes que utilizen en sus tutoriales, que no se encuentran ya disponibles en los entornos de Python y R en el JupyterHub. Para verificar si el paquete ya está incluído, consulten estos archivos por medio de una simple búsqueda:

- Python: 
  - conda-forge: https://github.com/oceanhackweek/jupyter-image/blob/main/py-base/conda-linux-64.lock
- R:
  - conda-forge: https://github.com/oceanhackweek/jupyter-image/blob/main/r/conda-linux-64.lock
  - CRAN y github (bloque marcado en amarillo): https://github.com/oceanhackweek/jupyter-image/blob/main/r/Dockerfile#L78-L96

Si no aparece ahí el nombre del paquete, por favor inclúyanlo en este issue lo antes posible. Yo lo añadiré a la "imagen" correspondiente.

**Por cada petición de paquetes, incluyan:**

- Python o R
- Nombre del paquete
- Se encuentra en conda-forge? Pueden consultarlo aquí https://conda-forge.org/feedstock-outputs/. Incluir el nombre exacto usado en conda-forge.
- Si no está en conda-forge, donde se encuentra? CRAN? PyPI? GitHub? Incluir el enlace a la fuente del paquete, y el nombre exacto usado en esa fuente

**Comment by lidefi87** [comment]
En mi primer tutorial tengo los siguientes paquetes de R: `tidyverse`, `rerddap`, `raster`, `lubridate`, `RColorBrewer`, y `rnaturalearth`. El segundo tutorial aún no lo termino porque sigo en búsqueda de un mejor set de datos. Este fin de semana lo termino.

**Comment by emiliom** [comment]
Gracias Denisse. Chequié en https://github.com/oceanhackweek/jupyter-image/blob/main/r/conda-linux-64.lock, y todos esos paquetes ya se encuentran en el entorno. Perfecto!

**Comment by LauraGomezNavarro** [comment]
En el tutorial de datos online uso (solo python): `numpy`, `matplotlib` ,  `cartopy` ,  `xarray ` ,  `cf_xarray` ,  `folium` ,  `seawater` ,  `palettable` ,  `datetime` ,  `json` ,  `erddapy

**Comment by emiliom** [comment]
Gracias Laura. Todos esos paquetes se encuentran en el entorno Python (https://github.com/oceanhackweek/jupyter-image/blob/main/py-base/conda-linux-64.lock). `datetime` y `json` son parte del standard library.

**Comment by LauraGomezNavarro** [comment]
Gracias Emilio. Para uno de los proyectos que no estamos planteando proponer nos haría falta un paquete bastante específico: `parcels` (conda create-c conda-forge parcels, https://oceanparcels.org/#installing).

**Comment by emiliom** [comment]
Paquetes a añadir en la próxima actualización de los entornos del jupyterhub:

### Python
- [x] `parcels` (conda-forge)
- [x] `windrose` (conda-forge)

### R 
- [x] `r-palmerpenguins` (conda-forge)
- [x] `satin` (CRAN)
- [x] `echogram` (https://github.com/hvillalo/echogram). Dependencias de echogram, que hay que instalar explícitamente:
  - [x] `r-mmand` (conda-forge)
  - [x] `readHAC` (CRAN)

**Comment by davecorrea** [comment]
Emilio, acabo de verificar que los paquetes que utilizó ya los mencionaron y se encuentran instalados, solo quedaría instalar la librería **windrose** de Python. Por favor podrías instalarlo [https://pypi.org/project/windrose].

**Comment by emiliom** [comment]
Muchas gracias @davecorrea . Ya confirmé que el paquete conda se encuentra en conda-forge, así que no anticipo ningún problema.

**Comment by hvillalo** [comment]
Emilio, en mi caso faltaría `palmerpenguins`, `satin` y `echogram` y sus dependencias. En el caso de echogram, necesitaría la versión del github (https://github.com/hvillalo/echogram). Otros paquetes que uso pero que ya aparecen en los enlaces que indicaste son `sp`, `lubridate`, `lattice` y `ggplot2`. Gracias!

**Comment by emiliom** [comment]
Gracias @hvillalo . `palmerpenguins` está en conda-forge y `satin` en CRAN. No espero ningún problema, pero como no sé mucho de R, no sé si las dependencias de `echogram` también se instalarán fácilmente. 

Haré la actualización de los entornos mañana viernes después de la reunión.

**Comment by emiliom** [comment]
@hvillalo me podrías apuntar a un archivo que enumere las dependencias de `echogram`? Es la lista en https://github.com/hvillalo/echogram/blob/master/DESCRIPTION, bajo `Imports:`?

**Comment by hvillalo** [comment]
Hola Emilio,

Muchas gracias! Si, esas son las dependenecias, básicamente faltaría

geosphere,
readHAC,
pals,
mmand,
data.table, plyr

Pendientes y gracias de nuevo por todo.

Héctor

--

Dr. Héctor Villalobos ***@***.******@***.***)>

Depto. de Pesquerías y Biología Marina

Instituto Politécnico Nacional-Centro

Interdisciplinario de Ciencias Marinas

CICIMAR-I.P.N.

A.P. 592. Colonia Centro

La Paz, Baja California Sur, MÉXICO. 23000

Tels.: (+52 612) 122 53 44; 123 46 58; 123 47 34 ext.: 81602

Fax: (+52 612) 122 53 22

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by emiliom** [comment]
Gracias. Parece que los únicos que no tenemos ya en el entorno son `readHAC` y `mmand`. `pals` lo tenemos, pero por favor confirmame si es https://github.com/kwstat/pals

Para `readHAC` y `mmand`, me podrías decir las fuentes de los paquetes, si CRAN o github? Y si es github, el enlace.

**Comment by emiliom** [comment]
Perdón, una actualización: `mmand` está en conda-forge. Entonces sólo necesito la información de `readHAC` y la confirmación de `pals`

**Comment by emiliom** [comment]
Asumo que `readHAC` es este paquete de CRAN? https://cran.r-project.org/web/packages/readHAC/index.html

**Comment by hvillalo** [comment]
Hola de nuevo Emilio,

Si, readHAC es el de CRAN. pals es la misma versión que esta en CRAN y github. Yo tengo el de CRAN.

--

Dr. Héctor Villalobos ***@***.******@***.***)>

Depto. de Pesquerías y Biología Marina

Instituto Politécnico Nacional-Centro

Interdisciplinario de Ciencias Marinas

CICIMAR-I.P.N.

A.P. 592. Colonia Centro

La Paz, Baja California Sur, MÉXICO. 23000

Tels.: (+52 612) 122 53 44; 123 46 58; 123 47 34 ext.: 81602

Fax: (+52 612) 122 53 22

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by emiliom** [comment]
Gracias! No sé si en el pasado alguien escogió la versión de pals de github por compatibilidad con otro paquete. Voy a comparar los dos, pero trataré de usar el de CRAN.

**Comment by emiliom** [comment]
Por lo que veo no parece haber gran diferencia con `pals` entre lo que está en github y [en CRAN](https://cran.r-project.org/web/packages/pals/). Creo que hay un poco menos riesgo para el entorno del JupyterHub si mantengo el uso del paquete de github, entonces eso haré.

**Comment by emiliom** [comment]
Hola. Ya actualizamos el jupyterhub con los nuevos paquetes. 
- El entorno de Python está bien, y aparecen los dos nuevos paquetes. 
- El entorno de R y RStudio también funciona. Pero yo no sé como confirmar que los nuevos paquetes están ahí y funcionan bien.  ~~Pero el de R causó problemas y por ahora RStudio no funciona! Ya reporté el problema y voy a esperar a ver qué diagnostican. Los mantendré al tanto.~~

**Comment by lidefi87** [comment]
@emiliom, acabo de caer en cuenta que el paquete `forecast` de R no está incluido en el ambiente. ¿Sería posible instalarlo? Lo vamos a usar en la sesión del miércoles. Disculpa por la demora en avisarte, no tuve tiempo de terminar el segundo tutorial hasta este fin de semana.

**Comment by emiliom** [comment]
Hola @lidefi87 . Heh, yo también descubrí hoy que tengo un paquete que voy a usar, de Python, que no había identificado porque hasta ayer y hoy he podido enfocarme bien en mi primer tutorial.

`forecast` no está en conda-forge, así que asumo que querés el de CRAN, https://cran.r-project.org/web/packages/forecast/index.html?

**Comment by lidefi87** [comment]
Gracias por responded tan pronto 😊 la versión de CRAN estaría bien, no tengo necesidad de una versión específica

**Comment by emiliom** [comment]
Hola de nuevo. Una complicación con los paquetes de R que no están en conda-forge es que parece que la resolución de dependencias no funciona bien. Entonces, tenemos que extraer manualmente la lista de dependencias del paquete, para incluirlas explícitamente. He hecho esto con `forecast` (del archivo https://github.com/robjhyndman/forecast/blob/master/DESCRIPTION), y esta es la lista de dependencias que no están ya en el entorno: `fracdiff`, `graphics`, `lmtest`, `stats`, `tseries`, `urca`. También `parallel`, pero te quería preguntar si no es lo mismo que `doparallel` o `parallelly`.

Ahora habrá que cruzar los dedos para que ninguna de esas dependencias tengan otras dependencias que no están instaladas! Probablemente no es prudente tratar de hacerlo hoy, el día antes del primer día.

**Comment by emiliom** [comment]
Paquetes a añadir en la próxima actualización de los entornos del jupyterhub:

### Python
- [x] `rasterstats` (conda-forge)

### R 
- [x] `forecast` (CRAN). Dependencias que hay que instalar explícitamente:
  - [x] `r-fracdiff` (conda-forge)
  - [x] `r-lmtest` (conda-forge)
  - [x] `r-tseries` (conda-forge)
  - [x] `r-urca` (conda-forge)
  - [ ] `graphics` **(CRAN?)**
  - [ ] `stats` **(CRAN?)**
  - [ ] `parallel` **??**

**Comment by emiliom** [comment]
@lidefi87 podrías confirmar mis preguntas sobre `graphics`, `stats` y `parallel`? 
- `graphics`: de CRAN?
- `stats`: de CRAN?
-  `parallel`: es diferente de `doparallel` y `parallelly`? Si es así, de donde lo tomamos, de CRAN?

**Comment by lidefi87** [comment]
Generalmente si se hace una instalación desde CRAN, todas las dependencias son instaladas automáticamente. Si este no es el caso, yo instalaría las que están disponibles en CRAN para evitar cualquier problema. Aunque para serte honesta, nunca he tenido que hacer esto, así que no estoy del todo segura que instalar paquetes desde conda resulte en problemas.

Según la página de [`forecast` en CRAN](https://cran.r-project.org/web/packages/forecast/index.html), estas son las dependencias:
```colorspace, fracdiff, generics (≥ 0.1.2), ggplot2 (≥ 2.2.1), graphics, lmtest, magrittr, nnet, parallel, Rcpp (≥ 0.11.0), stats, timeDate, tseries, urca, zoo```.

En cuanto a `parallel`, al parecer no es lo mismo que `doparallel` o `parallelly`.

**Comment by emiliom** [comment]
Gracias. Ahorita que estoy en RStudio noté que en el panel de arriba a la derecha, cuando selecciono "Global Environment", el drop down que aprece incluye "package:stats" y "package:graphics". Que casualidad más extraña! Podrías confirmar que efectivamente están instaladas? Si es así, el trabajo será más fácil.

**Comment by lidefi87** [comment]
Confirmo, a mí también me incluye `stats` y `graphics` bajo el _Global Environment_.

**Comment by emiliom** [comment]
@lidefi87 no encuentro `parallel` en CRAN. En cambio, parece que `parallely` es un paquete diseñado para sustituir directamente a `parallel`: https://parallelly.futureverse.org/
`parallely` ya está presente en el entorno.

¿Que pensás? ¿Es algo que podrías probar localmente, y me avisás si funciona? Estoy preparando la adición de paquetes de R que necesitás.

**Comment by lidefi87** [comment]
No estoy segura. ¿Te parece si lo dejamos como está? Yo lo instalé directamente en mi sesión y no demoró nada. Quizás esta sea la mejor opción.

**Comment by emiliom** [comment]
Anoche actualizamos el entorno con forecast, fractdiff, lmtest, tseries y urca. Cuando lo probés, talvez podés probar si parallely funciona como sustituto de parallel.

**Comment by emiliom** [comment]
Voy a cerrar este issue, para evitar confusiones en los nuevos eventos del 2024
